
<aside>
    
    <ul>
        <li><a href="<?php echo base_url(); ?>contact"><img src="<?php echo base_url('/assets/images/174598252.jpg')?>" alt="product info" height="150px" width="150px" /></a></li>
        <li><img src="<?php echo base_url('/assets/images/food.png')?>" alt="food posts" height="150px" width="150px" /></li>
        <li><img src="<?php echo base_url('/assets/images/106798813.jpg')?>" alt="baby posts" height="150px" width="150px" /></li>
    </ul>
    
</aside>
