<!DOCTYPE html>
<html lang="en-US" ng-app="Site">
    <head>
        <meta charset="UTF-8">
        <title>Mommy In The Making</title>
        <link rel="stylesheet" type="text/css" href="<?php base_url(); ?>/assets/css/main.css">
            
        <!--Main body text-->
        <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Give+You+Glory' rel='stylesheet' type='text/css'>
    </head>
    
    <body>
        <div id="main-wrapper">
             <header>
                <a href="<?php echo base_url(); ?>"><img src="<?php echo base_url('/assets/images/branding.png'); ?>" alt="Mommy In The Making" width="377" height="203" id="logo"></a>
                
                <div id="nav">
                    <ul>
                        <li><a href="<?php echo base_url(); ?>profile">Meet Mommy</a></li>
                        <li><a href="<?php echo base_url(); ?>contact">Contact</a></li>
                        <li><a href="<?php echo base_url(); ?>archive">Archive</a></li>
                    </ul>
                </div>
            </header>